# set up zfs packackes on system

#- include: zfs_windows.yml
#  when: ansible_os_family == "Windows"

- include: zfs_redhat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version > 7

#- include: zfs_debian.yml
#  when: ansible_distribution == "Debian" and ansible_distribution_major_version > 7

#- include: zfs_macos.yml
#  when: ansible_os_family == "Darwin"

# then continue to manage zfs things

# - include: zfs_manage.yml
